$id: https://ocr-d.github.io/schemas/v1/training-schema.json
type: object
required:
  - engineName
  - engineVersion
  - groundTruthBag
  - outputModelFormat
properties:
  engineName:
    type: string
    enum:
      - ocropus
      - kraken
      - tesseract
      - calamari
  engineVersion:
    type: string
  trainerArgs:
    description: Command line arguments passed to the CLI training tool
    type: array
    default: []
  recognizerArgs:
    description: Command line arguments passed to the CLI recognition tool
    type: array
    default: []
  groundTruthBag:
    description: A bag of line ground truth adhering to https://ocr-d.github.io/gt-profile.json
    type: string
  trainingGlob:
    description: Wildcard for matching only a subset of the ground truth files for training. Make sure to exclude extensions and end in '*'.
    type: 'string'
    default: '*'
    # type: array
    # default: ['*']
    # items:
      # type: string
  evaluationGlob:
    description: Wildcard for matching only a subset of the ground truth files for evaluationi. Make sure to exclude extensions and end in '*'.
    type: 'string'
    default: '*'
    # type: array
    # default: ['*']
    # items:
      # type: string
  outputModelFormat:
    description: The output format of the model. Note that individual engines only support a single one or a subset of formats.
    enum:
      - application/vnd.ocrd.pronn  # kraken < 1.0
      - application/vnd.ocrd.clstm  # ocropy-lpred, clstm, kraken<1.0
      - application/vnd.ocrd.coreml # kraken >= 1.0
      - application/vnd.ocrd.pyrnn  # ocropy-rpred
      - application/vnd.ocrd.tf+zip # calamari, zipped tensorflow data
      - application/vnd.ocrd.tesseract4  # tesseract >= 4.0.beta1
  validationRatio:
    description: Ratio of training vs. validation data to divide up ground truth
    type: number
    default: 0.9
  randomSeed:
    description: Seed for the random number generator shuffling the ground truth before dividing it into training vs. validation data
    type: integer
    default: 0
